# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

genres = Genre.create([{name: "Action Adventure"}, {name: "Comedy"}, {name: "Science Fiction"}, {name: "Drama"}, {name: "Horror"}, {name: "Documentary"}, {name: "Fantasy"}])
movies = Movie.create([{title: "Avengers: Age of Ultron", description: "When Tony Stark tries to jumpstart a dormant peace...", genre_id: 1, year_released: 2015, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Airplane!", description: "A straight-faced yet absurdist comedy about a burn...", genre_id: 2, year_released: 1980, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Terms of Endearment", description: "Following the mother-daughter relationship of Auro...", genre_id: 4, year_released: 1983, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Dumb & Dumber", description: "Two stupid guys, Lloyd (Carrey) and Harry (Daniels...", genre_id: 2, year_released: 1994, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Arrival", description: "When mysterious spacecraft touch down across the g...", genre_id: 3, year_released: 2016, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "The Ring", description: "In this remake of one of Japan's biggest box offic...", genre_id: 5, year_released: 2002, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Contact", description: "Jodie Foster stars as headstrong visionary astrono...", genre_id: 3, year_released: 1997, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "The Wizard of Oz", description: "Adapted from L. Frank Baum’s timeless children’s t...", genre_id: 7, year_released: 1939, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Die Hard", description: "When terrorists take over a Los Angeles skyscraper...", genre_id: 1, year_released: 1988, image_link: "https://static.metacritic.com/images/products/movi...">}, {title: "Star Trek II: The Wrath of Khan", description: "With the aide of the Enterprise crew, Admiral Kirk...", genre_id: 3, year_released: 1982, image_link: "https://static.metacritic.com/images/products/movi...">}])